#build:
#    docker build -t bioseed_bakta .

#start:
#    docker run -it --name bioseed_bakta -v /var/data/network/bakta:/host --network bioseed_network bioseed_bakta:latest

clean:
	docker stop bioseed_mmseqs2
	docker rm bioseed_mmseqs2
